// Case Studies — index gallery data model.
// 6 projects drawn from real Rifby work.
// Placeholders where real client names / metrics haven't been supplied yet.

const CASES = [
  {
    id: 'accountant-ai',
    client: 'Ahmad & Co Accountant',
    industry: 'Accounting',
    service: 'AI & Automation',
    categories: ['AI & Automation', 'Data / Analytics', 'Strategy'],
    headline: 'Manual reconciliation → AI-assisted close.',
    blurb: 'Transformed a solo accounting practice into an AI-powered firm. Reconciliation, categorisation, and client prep now run assisted by AI — freeing the owner to focus on advisory work.',
    metrics: [
      { v: '~70%', l: 'less time on close' },
      { v: '3×',   l: 'client capacity' },
    ],
    featured: true,
    thumb_pattern: 'dots',
    year: '2025',
  },
  {
    id: 'education-invoicing',
    client: 'ISW Consulting Ltd',
    industry: 'Education',
    service: 'AI & Automation',
    categories: ['AI & Automation', 'Strategy'],
    headline: 'Client invoicing, automated end-to-end.',
    blurb: 'Removed the invoicing bottleneck for a growing education business. Invoices are now raised, sent, and reconciled automatically from their student management system.',
    metrics: [
      { v: '~15 hrs', l: 'saved / week' },
      { v: '0',       l: 'missed invoices' },
    ],
    thumb_pattern: 'stripes',
    year: '2025',
  },
  {
    id: 'gaming-app',
    client: 'Tmtam Studio for Game Development W.L.L',
    industry: 'Gaming',
    service: 'App Development',
    categories: ['App Development', 'Strategy'],
    headline: 'Companion app for a flagship game product.',
    blurb: 'Designed and built a mobile companion app around a live gaming product — extending the player experience beyond the core game.',
    metrics: [
      { v: 'iOS + Android', l: 'shipped platforms' },
      { v: '6 wk',          l: 'to first release' },
    ],
    thumb_pattern: 'dots',
    year: '2025',
  },
  {
    id: 'another-world-social',
    client: 'Another World',
    location: 'Camberley',
    industry: 'Gaming',
    service: 'Social Media Automation',
    categories: ['Social Media Automation', 'AI & Automation'],
    headline: 'Social scheduling on autopilot.',
    blurb: 'Built a cross-platform social pipeline for Another World. One content upload publishes across their channels on the right schedule — no more copy-pasting between apps.',
    metrics: [
      { v: '~8 hrs', l: 'saved / week' },
      { v: '4',      l: 'platforms synced' },
    ],
    thumb_pattern: 'dots',
    year: '2025',
  },
  {
    id: 'education-site',
    client: 'Markwork Ltd',
    industry: 'Education',
    service: 'Web Development',
    categories: ['Web Development'],
    headline: 'A website that sells the service, not just lists it.',
    blurb: 'Full redesign + rebuild of an education provider\'s site. Conversion-focused architecture, fast load, CMS the team actually uses.',
    metrics: [
      { v: 'Fully custom', l: 'design & build' },
    ],
    thumb_pattern: 'stripes',
    year: '2025',
  },
  {
    id: 'food-site',
    client: "Hunny's Taste",
    industry: 'Food & Hospitality',
    service: 'Web Development',
    categories: ['Web Development'],
    headline: 'A food brand website built for ordering.',
    blurb: 'Brand-led site for a food business — designed to convert visitors into orders with minimal friction and a menu system the owner can manage themselves.',
    metrics: [
      { v: 'Brand + build', l: 'delivered' },
    ],
    thumb_pattern: 'stripes',
    year: '2025',
  },

  // ── Additional / illustrative case studies ──────────────────────────
  {
    id: 'law-intake',
    client: 'Hartwell & Vine Solicitors',
    industry: 'Legal',
    service: 'AI & Automation',
    categories: ['AI & Automation', 'Data / Analytics'],
    headline: 'AI intake that triages cases in minutes.',
    blurb: 'Built an AI client-intake assistant for a mid-sized law firm. New enquiries are summarised, classified by practice area, and routed to the right solicitor with a draft response ready to send.',
    metrics: [
      { v: '~12 min', l: 'per intake (was 45)' },
      { v: '96%',     l: 'routing accuracy' },
    ],
    thumb_pattern: 'dots',
    year: '2025',
  },
  {
    id: 'clinic-booking',
    client: 'Meridian Dental Group',
    industry: 'Healthcare',
    service: 'App Development',
    categories: ['App Development', 'AI & Automation'],
    headline: 'Booking app that fills the no-show gap.',
    blurb: 'Patient booking app with an AI waitlist — when someone cancels, the system finds the next patient who fits the slot and confirms them automatically.',
    metrics: [
      { v: '−38%',   l: 'no-show rate' },
      { v: '£24k',   l: 'recovered / yr' },
    ],
    thumb_pattern: 'stripes',
    year: '2024',
  },
  {
    id: 'retail-inventory',
    client: 'Kestrel Home',
    industry: 'Retail',
    service: 'Data / Analytics',
    categories: ['Data / Analytics', 'AI & Automation', 'Strategy'],
    headline: 'Demand forecasting for a boutique homeware brand.',
    blurb: 'Forecasting dashboard that pulls sales, seasonality, and supplier lead times into a single re-order recommendation — cutting stockouts and overstock in the same breath.',
    metrics: [
      { v: '−42%',  l: 'stockouts' },
      { v: '£60k',  l: 'less tied-up stock' },
    ],
    thumb_pattern: 'dots',
    year: '2024',
  },
  {
    id: 'realestate-portal',
    client: 'Ashdown Property',
    industry: 'Real Estate',
    service: 'Web Development',
    categories: ['Web Development', 'App Development'],
    headline: 'Client portal that replaces the email thread.',
    blurb: 'Lettings and sales portal that gives landlords and tenants a single source of truth — documents, payments, maintenance requests, all in one place.',
    metrics: [
      { v: '~20 hrs', l: 'admin saved / week' },
      { v: '4.8 ★',   l: 'client rating' },
    ],
    thumb_pattern: 'stripes',
    year: '2024',
  },
  {
    id: 'fitness-social',
    client: 'Iron & Oak Studio',
    industry: 'Fitness',
    service: 'Social Media Automation',
    categories: ['Social Media Automation', 'AI & Automation'],
    headline: 'A month of content from one afternoon of filming.',
    blurb: 'AI-assisted content pipeline for an independent gym — long-form workout footage is auto-cut into reels, captioned, and scheduled across platforms.',
    metrics: [
      { v: '5×',   l: 'posting cadence' },
      { v: '+180%', l: 'reach in 90 days' },
    ],
    thumb_pattern: 'dots',
    year: '2025',
  },
  {
    id: 'nonprofit-crm',
    client: 'Thornfield Trust',
    industry: 'Non-profit',
    service: 'Strategy',
    categories: ['Strategy', 'Data / Analytics', 'AI & Automation'],
    headline: 'From six spreadsheets to one donor CRM.',
    blurb: 'Consolidated a charity\'s donor, volunteer, and grant tracking into a single lightweight CRM — with AI-drafted thank-you letters that keep the personal tone.',
    metrics: [
      { v: '6 → 1',  l: 'systems' },
      { v: '+22%',   l: 'repeat donors' },
    ],
    thumb_pattern: 'stripes',
    year: '2024',
  },
  {
    id: 'logistics-ops',
    client: 'Ferry Lane Logistics',
    industry: 'Logistics',
    service: 'AI & Automation',
    categories: ['AI & Automation', 'Data / Analytics'],
    headline: 'Dispatch assistant for a 30-van fleet.',
    blurb: 'AI dispatch tool that reads incoming jobs, assigns the best van by location and load, and notifies the driver — what used to take an operator all morning now runs in the background.',
    metrics: [
      { v: '~3 hrs', l: 'saved / day' },
      { v: '−11%',   l: 'fuel cost' },
    ],
    thumb_pattern: 'dots',
    year: '2025',
  },
  {
    id: 'travel-concierge',
    client: 'Wayfare & Co.',
    industry: 'Travel',
    service: 'App Development',
    categories: ['App Development', 'AI & Automation'],
    headline: 'AI concierge for a boutique travel agent.',
    blurb: 'Private-label travel app with an AI concierge that drafts itineraries, handles common questions, and escalates to a human advisor when it matters.',
    metrics: [
      { v: '24/7',  l: 'response' },
      { v: '+31%',  l: 'booking conversion' },
    ],
    thumb_pattern: 'stripes',
    year: '2024',
  },
];

const CATEGORIES = [
  'All',
  'AI & Automation',
  'App Development',
  'Web Development',
  'Social Media Automation',
  'Data / Analytics',
  'Strategy',
];

window.CASES = CASES;
window.CATEGORIES = CATEGORIES;
